<?php 

class NamesFactory{
	public static $arrayNames = [
		'Aberta Demais De Oliveira',
		'Abias Corpus Da Silva',
		'Ácido Acético Etílico Da Silva',
		'Alfredo Prazeirozo Texugueiro',
		'Amável Pinto',
		'Ambrísia Estilingue Morretes',
		'Ana Baiana Meleva Daqui Pratinhos',
		'Antonio Buceta Agudim',
		'Antonio Donizete Bobo',
		'Antonio Manso Pacífico De Oliveira Sossegado',
		'Antônio Morrendo Das Dores',
		'Antônio Veado Prematuro',
		'Ava Gina',
		'Barrigudinha Seleida',
		'Benvindo Viola',
		'Bucetildes Fernandes',
		'Carabino Tiro Certo',
		'Chevrolet Da Silva Ford',
		'Colapso Cardíaco da Silva',
		'Defuntina De Souza Cruz',
		'Delícia Costa Melo',
		'Deuzivaldo Ferreira',
		'Domingos Pinto Justo',
		'Dosolina Piroca Tazinasso',
		'Elvis Presley Da Silva',
		'Eraldonclóbes Souza',
		'Espere Em Deus Mateus',
		'Eva Gina Melo',
		'Falidora Da Fortuna Dopai Ramiro',
		'Faraó do Egito Sousa',
		'Finadina de Souza Cruz',
		'Flávio Cavalcante Rei da Televisão',
		'Fodelícia Dos Santos',
		'Francisco Zebedeu Sanguessuga',
		'Himineu Casamenticio Das Dores Conjugais',
		'Inocêncio Coitadinho',
		'Jacinto Leite Aquino Rêgo',
		'Jacinto Pinto',
		'Jacinto Regoroxo',
		'Jafa Lei Dos Santos',
		'Janeiro Fevereiro de Março Abril',
		'Jean Claude Van Dame Da Silva',
		'João Da Cú Da Luz',
		'João Manuel Boceta Portas',
		'João Sem Sobrenome',
		'Joaquim Pinto Molhadinho',
		'José Catarrinho',
		'Josefina Grosso',
		'Jotacá Dois Mil e Um',
		'Júlio Santos Pé-Curto',
		'Juvenalda Datia Gulosa',
		'Letsgo Daqui',
		'Madeinusa',
		'Maiquel Edy Marfy',
		'Manuel Sola De Sá Pato',
		'Maria Bastarda Dequem',
		'Maria Buceta Paranhos Pinto',
		'Maria Cristina Do Pinto Magro',
		'Maria Da Boa Morte',
		'Maria Da Delícia Dazona',
		'Maria Do Bom Despacho',
		'Maria José Brochado',
		'Maria Panela',
		'Maria Tributina Prostituta Cataerva',
		'Mariana Daxana Laranjal',
		'Maycom Géquiçom',
		'Merdolino Mendonça',
		'Metia Paula Da Silva',
		'Mijardina Pinto',
		'Miquetiçon Dos Santos',
		'Mitiko Kudo Endo',
		'Necrotério Pereira Da Silva',
		'Orlando Modesto Pinto',
		'Patricia Pinto Grosso',
		'Pernilonguildo Tentofaz Furão',
		'Piá Motel Das Dores',
		'Pinto Brochado',
		'Pinto Crespo Magalhães',
		'Produto do Amor Conjugal De Marichá E Maribel',
		'Putassa Frescura',
		'Rego Penteado',
		'Remédio Amargo',
		'Rolando Caio da Rocha',
		'Rolando Escadabaixo',
		'Safada Da Sogra Vitorina',
		'Safira Azul Esverdeada',
		'Salvador Das Dores',
		'Seriaela Deu',
		'Sextavado Obtusângulo Reto',
		'Silvio Dubroca',
		'Simplício Simplório Da Simplicidade Simples',
		'Timétio Pinto',
		'Tobiniana Matusquela',
		'Última Delícia do Casal Carvalho',
		'Um Dois Três de Oliveira Quatro',
		'Vanessa Cachorroski',
		'Vicente Mais Ou Menos de Souza',
		'Vitor Hugo Tocagaita',
		'Zélia Tocafundo Pinto'
	]; 

	public static function getName(){
		return self::$arrayNames[mt_rand(0, count(self::$arrayNames)-1)]; 
	}
}