<?php 

class NamesFactory{
	public static $arrayNames = [
		"Adam Link",
		"I, Robot (Eando Binder)",
		"Alfie",
		"Barbarella",
		"Alpha 60",
		"Alphaville",
		"Alsatia Zevo",
		"Toys", 
		"ARDVARC",
		"Ash Alien",
		"B.O.B.", 
		"Bender",
		"Bishop",	
		"BOSS", 
		"Brackenridge",	
		"C-3P0",	
		"Cambot",	
		"Cassandra One",	
		"Android",
		"Cherry 2000",	
		"Conky 2000",
		"Crow T. Robot",
		"Cutie",
		"Isaac Asimov",
		"D.A.R.Y.L",
		"D84",
		"Dr. Who",
		"Data",	
		"Dot Matrix",
		"Spaceballs",
		"Dynak X",	
		"Ed-209",	
		"Robocop",
		"Emma-2",	
		"Epideme",	
		"Red Dwarf",
		"EV-9D9",	
		"Star Wars",
		"Ez-35",	
		"Gir Invader Zim",
		"Gort",	
		"Gypsy",
		"H.E.L.P.eR.", 
		"Hal 9000",
		"Hawk Buck Rogers",
		"Hudzen 10",
		"Irona	Richie Rich's maid",
		"JANICE",
		"Jet Jaguar",	
		"Godzilla", 
		"Jinx",	
		"SpaceCamp",
		"Johnny-5",	
		"Short Circuit",
		"K-9",	
		"Kamelion",	
		"KARR", 
		"KITT", 
		"knight Rider",
		"Kryten",
		"L-76",	
		"Landru",
		"Lenny",	
		"Leon Kowalski",	
		"Blade Runner",
		"Max 404 Android",
		"Max Headroom",	
		"Maximillian",	
		"Mr. R.I.N.G",
		"Omnius",
		"Dune",
		"Orak",	
		"Blake's 7",
		"Pris",	
		"Queeg",	
		"R2-D2",	
		"R5-D4",	
		"Rachael",	
		"Robby",		
		"Robot B-9",	
		"Roy Batty",	
		"S.T.A.R.",
		"Slave",
		"Speedy",	
		"Synergy Jem & the Holograms",
		"T-800",	
		"Tom Servo",
		"Tony",	
		"Twiki",
		"Vaal",	
		"WOTAN",
		"Zen Blake's 7",
		"Zero",	
		"Zhora"	
	]; 

	public static function getName(){
		return self::$arrayNames[mt_rand(0, count(self::$arrayNames)-1)]; 
	}
}

